export { generateAiCareAdvice, getAiCareRules } from "./aiCareService";
export { getAdminDashboardStats } from "./adminService";
export { getBreedById, getBreedList } from "./breedService";
export { getFunFacts } from "./funFactService";
export { getGamificationConfig } from "./gamificationService";
export { getCollectionCards, getHeroImages, getHomeConfig, getPageHeroImages, getSmartEcosystem } from "./homepageService";
export { getNavigationItems } from "./navigationService";
export { getNewsById, getNewsList } from "./newsService";
export { getPhotoAssets } from "./photoService";
export { getCoreProduct, getProductBySlug, getProducts } from "./productService";
export { getServices } from "./serviceService";
